/**
 * Production-ready constants and utilities for cooking ingredients and diet metadata.
 */

export type DietProfile =
    | "vegan"
    | "vegetarian"
    | "egg-eater"
    | "fish-eater"
    | "omnivore";

export const DIET_PROFILES: Set<DietProfile> = new Set([
    "vegan",
    "vegetarian",
    "egg-eater",
    "fish-eater",
    "omnivore",
]);

export interface Ingredient {
    id: string;
    name: string;
    synonyms: string[];
    foodGroup:
    | "vegetable"
    | "fruit"
    | "spice"
    | "herb"
    | "grain"
    | "dairy"
    | "protein" // meat, poultry, etc. grouped generally or specific
    | "meat"
    | "poultry"
    | "seafood"
    | "legume"
    | "oil"
    | "condiment"
    | "baking"
    | "nut"
    | "beverage"
    | "other";
    containsAnimal: boolean;
    animalType: "meat" | "poultry" | "fish" | "dairy" | "egg" | "bee" | null;
    isVegan: boolean;
    isVegetarian: boolean;
    isPescatarian: boolean;
    commonIn?: string[];
}

export const ALL_INGREDIENTS: Ingredient[] = [
    // --- Vegetables ---
    {
        id: "onion",
        name: "onion",
        synonyms: ["yellow onion", "brown onion", "red onion"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "garlic",
        name: "garlic",
        synonyms: ["garlic clove"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "tomato",
        name: "tomato",
        synonyms: ["tomatoes"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "potato",
        name: "potato",
        synonyms: ["potatoes", "spud"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "carrot",
        name: "carrot",
        synonyms: ["carrots"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "spinach",
        name: "spinach",
        synonyms: ["palak"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "broccoli",
        name: "broccoli",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western", "asian"],
    },
    {
        id: "cauliflower",
        name: "cauliflower",
        synonyms: ["gobi"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "bell-pepper",
        name: "bell pepper",
        synonyms: ["capsicum", "sweet pepper", "paprika"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "mushroom",
        name: "mushroom",
        synonyms: ["button mushroom", "champignon"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "ginger",
        name: "ginger",
        synonyms: ["ginger root"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian", "indian"],
    },
    {
        id: "chili-pepper",
        name: "chili pepper",
        synonyms: ["chilli", "hot pepper", "red pepper", "green chilli"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "zucchini",
        name: "zucchini",
        synonyms: ["courgette"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["mediterranean", "western"],
    },
    {
        id: "eggplant",
        name: "eggplant",
        synonyms: ["aubergine", "brinjal"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["mediterranean", "asian", "indian"],
    },
    {
        id: "cucumber",
        name: "cucumber",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "lettuce",
        name: "lettuce",
        synonyms: ["iceberg", "romaine"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "kale",
        name: "kale",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "sweet-potato",
        name: "sweet potato",
        synonyms: ["yam"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "green-bean",
        name: "green bean",
        synonyms: ["string bean", "snap bean", "french bean"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "peas",
        name: "peas",
        synonyms: ["green peas", "garden peas"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "corn",
        name: "corn",
        synonyms: ["sweet corn", "maize"],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cabbage",
        name: "cabbage",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "celery",
        name: "celery",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "asparagus",
        name: "asparagus",
        synonyms: [],
        foodGroup: "vegetable",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "avocado",
        name: "avocado",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["mexican", "western"],
    },

    // --- Fruits ---
    {
        id: "lemon",
        name: "lemon",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "lime",
        name: "lime",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "apple",
        name: "apple",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "banana",
        name: "banana",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "orange",
        name: "orange",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "strawberry",
        name: "strawberry",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "blueberry",
        name: "blueberry",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "mango",
        name: "mango",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian", "indian", "latin american"],
    },
    {
        id: "pineapple",
        name: "pineapple",
        synonyms: [],
        foodGroup: "fruit",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian", "latin american"],
    },

    // --- Grains & Legumes ---
    {
        id: "rice",
        name: "rice",
        synonyms: ["white rice", "brown rice", "basmati", "jasmine"],
        foodGroup: "grain",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "pasta",
        name: "pasta",
        synonyms: ["spaghetti", "penne", "macaroni", "noodles"],
        foodGroup: "grain",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["italian", "western"],
    },
    {
        id: "bread",
        name: "bread",
        synonyms: ["loaf", "slice"],
        foodGroup: "grain",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "quinoa",
        name: "quinoa",
        synonyms: [],
        foodGroup: "grain",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["latin american", "western"],
    },
    {
        id: "oats",
        name: "oats",
        synonyms: ["oatmeal", "rolled oats"],
        foodGroup: "grain",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "lentils",
        name: "lentils",
        synonyms: ["dal", "daal", "red lentils", "brown lentils"],
        foodGroup: "legume",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["indian", "middle eastern"],
    },
    {
        id: "chickpeas",
        name: "chickpeas",
        synonyms: ["garbanzo beans", "chana"],
        foodGroup: "legume",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["middle eastern", "indian", "mediterranean"],
    },
    {
        id: "black-beans",
        name: "black beans",
        synonyms: [],
        foodGroup: "legume",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["latin american"],
    },
    {
        id: "kidney-beans",
        name: "kidney beans",
        synonyms: ["rajma"],
        foodGroup: "legume",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["indian", "latin american"],
    },
    {
        id: "tofu",
        name: "tofu",
        synonyms: ["bean curd"],
        foodGroup: "legume",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian"],
    },

    // --- Meat & Poultry ---
    {
        id: "chicken-breast",
        name: "chicken breast",
        synonyms: ["chicken"],
        foodGroup: "poultry",
        containsAnimal: true,
        animalType: "poultry",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["global"],
    },
    {
        id: "chicken-thigh",
        name: "chicken thigh",
        synonyms: [],
        foodGroup: "poultry",
        containsAnimal: true,
        animalType: "poultry",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["global"],
    },
    {
        id: "ground-beef",
        name: "ground beef",
        synonyms: ["minced meat", "mince"],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["western", "latin american"],
    },
    {
        id: "steak",
        name: "steak",
        synonyms: ["beef steak"],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["western"],
    },
    {
        id: "pork-chop",
        name: "pork chop",
        synonyms: [],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["western", "asian"],
    },
    {
        id: "bacon",
        name: "bacon",
        synonyms: [],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["western"],
    },
    {
        id: "sausage",
        name: "sausage",
        synonyms: [],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["global"],
    },
    {
        id: "turkey",
        name: "turkey",
        synonyms: [],
        foodGroup: "poultry",
        containsAnimal: true,
        animalType: "poultry",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["western"],
    },
    {
        id: "lamb",
        name: "lamb",
        synonyms: ["mutton"],
        foodGroup: "meat",
        containsAnimal: true,
        animalType: "meat",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: false,
        commonIn: ["middle eastern", "indian", "western"],
    },

    // --- Seafood ---
    {
        id: "salmon",
        name: "salmon",
        synonyms: [],
        foodGroup: "seafood",
        containsAnimal: true,
        animalType: "fish",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "tuna",
        name: "tuna",
        synonyms: [],
        foodGroup: "seafood",
        containsAnimal: true,
        animalType: "fish",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "shrimp",
        name: "shrimp",
        synonyms: ["prawns"],
        foodGroup: "seafood",
        containsAnimal: true,
        animalType: "fish",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cod",
        name: "cod",
        synonyms: [],
        foodGroup: "seafood",
        containsAnimal: true,
        animalType: "fish",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "tilapia",
        name: "tilapia",
        synonyms: [],
        foodGroup: "seafood",
        containsAnimal: true,
        animalType: "fish",
        isVegan: false,
        isVegetarian: false,
        isPescatarian: true,
        commonIn: ["global"],
    },

    // --- Dairy & Eggs ---
    {
        id: "milk",
        name: "milk",
        synonyms: ["cow milk", "whole milk"],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cheese",
        name: "cheese",
        synonyms: ["cheddar", "mozzarella"],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "butter",
        name: "butter",
        synonyms: [],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western", "indian"],
    },
    {
        id: "yogurt",
        name: "yogurt",
        synonyms: ["curd", "yoghurt"],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cream",
        name: "cream",
        synonyms: ["heavy cream"],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western", "indian"],
    },
    {
        id: "egg",
        name: "egg",
        synonyms: ["eggs"],
        foodGroup: "dairy", // Often grouped here or separate
        containsAnimal: true,
        animalType: "egg",
        isVegan: false,
        isVegetarian: false, // Strict vegetarian (lacto) doesn't eat eggs, but often "vegetarian" implies lacto-ovo. We'll use strict flags.
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "parmesan",
        name: "parmesan",
        synonyms: ["parmigiano"],
        foodGroup: "dairy",
        containsAnimal: true,
        animalType: "dairy",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["italian"],
    },

    // --- Oils & Fats ---
    {
        id: "olive-oil",
        name: "olive oil",
        synonyms: ["evoo"],
        foodGroup: "oil",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["mediterranean", "global"],
    },
    {
        id: "vegetable-oil",
        name: "vegetable oil",
        synonyms: ["canola oil", "sunflower oil"],
        foodGroup: "oil",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "coconut-oil",
        name: "coconut oil",
        synonyms: [],
        foodGroup: "oil",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian", "indian"],
    },
    {
        id: "sesame-oil",
        name: "sesame oil",
        synonyms: [],
        foodGroup: "oil",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian"],
    },

    // --- Spices & Herbs ---
    {
        id: "salt",
        name: "salt",
        synonyms: ["sea salt", "kosher salt"],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "black-pepper",
        name: "black pepper",
        synonyms: ["pepper"],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cumin",
        name: "cumin",
        synonyms: ["jeera"],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["indian", "middle eastern", "latin american"],
    },
    {
        id: "turmeric",
        name: "turmeric",
        synonyms: ["haldi"],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["indian", "asian"],
    },
    {
        id: "paprika",
        name: "paprika",
        synonyms: [],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western", "mediterranean"],
    },
    {
        id: "cinnamon",
        name: "cinnamon",
        synonyms: [],
        foodGroup: "spice",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "basil",
        name: "basil",
        synonyms: [],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["italian", "thai"],
    },
    {
        id: "parsley",
        name: "parsley",
        synonyms: [],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western", "middle eastern"],
    },
    {
        id: "cilantro",
        name: "cilantro",
        synonyms: ["coriander"],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["latin american", "indian", "asian"],
    },
    {
        id: "rosemary",
        name: "rosemary",
        synonyms: [],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "thyme",
        name: "thyme",
        synonyms: [],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "oregano",
        name: "oregano",
        synonyms: [],
        foodGroup: "herb",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["italian", "mediterranean"],
    },

    // --- Condiments & Baking ---
    {
        id: "sugar",
        name: "sugar",
        synonyms: ["white sugar"],
        foodGroup: "baking",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "flour",
        name: "flour",
        synonyms: ["all-purpose flour", "wheat flour"],
        foodGroup: "baking",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "soy-sauce",
        name: "soy sauce",
        synonyms: ["soya sauce"],
        foodGroup: "condiment",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["asian"],
    },
    {
        id: "vinegar",
        name: "vinegar",
        synonyms: ["white vinegar", "apple cider vinegar"],
        foodGroup: "condiment",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "honey",
        name: "honey",
        synonyms: [],
        foodGroup: "condiment",
        containsAnimal: true,
        animalType: "bee",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "mayonnaise",
        name: "mayonnaise",
        synonyms: ["mayo"],
        foodGroup: "condiment",
        containsAnimal: true,
        animalType: "egg",
        isVegan: false,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "ketchup",
        name: "ketchup",
        synonyms: ["tomato sauce"],
        foodGroup: "condiment",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "mustard",
        name: "mustard",
        synonyms: [],
        foodGroup: "condiment",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "peanut-butter",
        name: "peanut butter",
        synonyms: [],
        foodGroup: "nut",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["western"],
    },
    {
        id: "almonds",
        name: "almonds",
        synonyms: [],
        foodGroup: "nut",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "walnuts",
        name: "walnuts",
        synonyms: [],
        foodGroup: "nut",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
    {
        id: "cashews",
        name: "cashews",
        synonyms: [],
        foodGroup: "nut",
        containsAnimal: false,
        animalType: null,
        isVegan: true,
        isVegetarian: true,
        isPescatarian: true,
        commonIn: ["global"],
    },
];

/**
 * A Map of ingredient names/synonyms to the full Ingredient object for O(1) lookup.
 */
export const INGREDIENT_INDEX: Record<string, Ingredient> = {};
export const INGREDIENT_NAME_SET = new Set<string>();

ALL_INGREDIENTS.forEach((ing) => {
    INGREDIENT_INDEX[ing.name] = ing;
    INGREDIENT_NAME_SET.add(ing.name);
    ing.synonyms.forEach((syn) => {
        INGREDIENT_INDEX[syn] = ing;
        INGREDIENT_NAME_SET.add(syn);
    });
});

/**
 * Checks if a given string is a valid ingredient name or synonym.
 * @param name - The ingredient name to check (case-insensitive).
 * @returns True if the ingredient exists in the database.
 */
export function isValidIngredient(name: string): boolean {
    return INGREDIENT_NAME_SET.has(name.toLowerCase());
}

/**
 * Returns normalized ingredient name if valid.
 * If invalid, throw an error with message:
 * "No such ingredient: <name>. Please choose from the available ingredients."
 */
export function validateIngredientOrError(name: string): string {
    const normalized = name.toLowerCase();
    if (!isValidIngredient(normalized)) {
        throw new Error(
            `No such ingredient: ${name}. Please choose from the available ingredients.`
        );
    }
    return INGREDIENT_INDEX[normalized].name;
}

/**
 * Filters a list of ingredient names based on selected diet.
 * If an ingredient does not exist in constants.ts, it must NOT be included.
 */
export function filterIngredientsByDiet(
    ingredientNames: string[],
    diet: DietProfile
): string[] {
    return ingredientNames.filter((name) => {
        const normalized = name.toLowerCase();
        const ingredient = INGREDIENT_INDEX[normalized];
        if (!ingredient) return false;

        if (diet === "omnivore") return true;
        if (diet === "vegan") return ingredient.isVegan;
        if (diet === "vegetarian") return ingredient.isVegetarian;
        if (diet === "egg-eater")
            return ingredient.isVegetarian || ingredient.animalType === "egg";
        if (diet === "fish-eater") return ingredient.isPescatarian;

        return false;
    });
}

/**
 * Returns recommended ingredients for a given diet.
 * Should return any ingredients that fit the diet profile.
 * Example: if user selects vegetarian, return veg-friendly ingredients only.
 */
export function recommendedIngredientsForDiet(diet: DietProfile): string[] {
    return ALL_INGREDIENTS.filter((ingredient) => {
        if (diet === "omnivore") return true;
        if (diet === "vegan") return ingredient.isVegan;
        if (diet === "vegetarian") return ingredient.isVegetarian;
        if (diet === "egg-eater")
            return ingredient.isVegetarian || ingredient.animalType === "egg";
        if (diet === "fish-eater") return ingredient.isPescatarian;
        return false;
    }).map((ing) => ing.name);
}
